#!/bin/sh

set -e
sudo setcap 'cap_sys_nice=eip' /usr/bin/modem
adduser --system broadcast
addgroup --system broadcast
usermod -a -G plugdev broadcast
sudo systemctl enable rt-mbms-modem
sudo systemctl restart rt-mbms-modem
#DEBHELPER#
